apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-front-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library-front
  template:
    metadata:
      labels:
        app: library-front
    spec:
      containers:
      - name: library-front-container
        # ▼ [복구 완료] 다시 사용자님의 개인 레포지토리 주소로 변경했습니다!
        image: 416225317325.dkr.ecr.us-east-2.amazonaws.com/hcoh-library-proj:latest
        ports:
        - containerPort: 80