apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-front-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: library-front
  template:
    metadata:
      labels:
        app: library-front
    spec:
      containers:
      - name: library-front-container
        # ▼ 여기를 인프라 팀이 준 'frontend' 주소로 변경했습니다!
        image: 416225317325.dkr.ecr.us-east-2.amazonaws.com/aivle-bookservice-team5-frontend:latest
        ports:
        - containerPort: 80